import "./globals.css";

export const metadata = {
  title: "Ujaan Das",
  description: "Generated by the Aforementioned...",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body id="app">{children}</body>
    </html>
  );
}
